### ISSUE TITLE
Wrong topics `awsome` and `awsome-list`

### ISSUE THREAD

**Issue by reisdev** [bitrise-dev/awesome-bitrise#2]
## What

The repo topics have a typo and that may impact the reach of this content. The right `topics` should be `awesome` and `awesome-list`.

## How to fix

Edit the current topics and remove the `awsome` and `awsome-list` topics. Then, add the right ones, `awesome` and `awesome-list`

**Comment by moatazeldebsy** [comment]
Thank you @reisdev , I fixed it
